/**
 * The assets someone meets in the first minute, rendered for real.
 *
 * A link preview reads a PNG, not an SVG, and a browser tab wants an .ico — so
 * the identity has to exist as pixels somewhere. Nothing in the toolchain
 * rasterises text, and adding a rasteriser to ship two images is a dependency
 * bought for a build step. Chrome is already on the machine that renders this,
 * and the scenario allows a committed render: this script draws the pages with
 * headless Chrome and writes the files into `public/`, where they are committed
 * and never regenerated by the site build.
 *
 * Nothing on the card is written here. The words come from `src/lib/copy.ts`,
 * the palette from `tokens.css`, the layout from `src/lib/social-card.ts` and
 * the numbers from the dataset — the first cut of this script retyped all four,
 * so the card could quietly disagree with the product about what the product
 * says (Standards review, 2026-09-07).
 *
 * Each render writes `public/social-card.json` beside the image: the facts the
 * image was drawn from. `--check` re-reads the dataset and fails when the image
 * no longer tells the truth — a route added, a value re-read, the tagline
 * changed — which existence-and-size could never notice.
 *
 *   node scripts/render-assets.mjs         # re-render into public/
 *   node scripts/render-assets.mjs --check # verify what is committed, change nothing
 */
import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { chromePath } from "./chrome.mjs";

const root = fileURLToPath(new URL("..", import.meta.url));
const publicDir = join(root, "public");
const check = process.argv.includes("--check");

const CARD = { width: 1200, height: 630 };
const ICON_SIZES = [16, 32, 64];
const SIDECAR = "social-card.json";

function shoot(html, width, height, out) {
  const dir = join(tmpdir(), `permit-rulebook-assets-${process.pid}`);
  mkdirSync(dir, { recursive: true });
  const page = join(dir, "page.html");
  writeFileSync(page, html, "utf8");
  execFileSync(chromePath(), [
    "--headless", "--disable-gpu", "--hide-scrollbars", "--force-device-scale-factor=1",
    `--window-size=${width},${height}`, `--screenshot=${out}`,
    pathToFileURL(page).href,
  ], { stdio: "ignore" });
  rmSync(dir, { recursive: true, force: true });
  const png = readFileSync(out);
  const w = png.readUInt32BE(16), h = png.readUInt32BE(20);
  if (w !== width || h !== height) throw new Error(`${out}: rendered ${w}x${h}, wanted ${width}x${height}`);
  return png;
}

/** The mark, at whatever size is asked for, drawn from the committed SVG so the
 * tab icon and the .ico can never be two different drawings. */
const markPage = (size) => `<!doctype html><meta charset="utf-8"><style>
  html, body { margin: 0; padding: 0; width: ${size}px; height: ${size}px; overflow: hidden; }
  img { display: block; width: ${size}px; height: ${size}px; }
</style><img src="favicon.svg" alt="">`;

/** An .ico is a six-byte header, one sixteen-byte entry per size, and the PNGs
 * themselves. A size of 256 is written as 0; ours are all smaller. */
function ico(images) {
  const header = Buffer.alloc(6);
  header.writeUInt16LE(0, 0);
  header.writeUInt16LE(1, 2);
  header.writeUInt16LE(images.length, 4);
  let offset = 6 + images.length * 16;
  const entries = [];
  for (const { size, png } of images) {
    const e = Buffer.alloc(16);
    e.writeUInt8(size >= 256 ? 0 : size, 0);
    e.writeUInt8(size >= 256 ? 0 : size, 1);
    e.writeUInt8(0, 2);
    e.writeUInt8(0, 3);
    e.writeUInt16LE(1, 4);
    e.writeUInt16LE(32, 6);
    e.writeUInt32LE(png.length, 8);
    e.writeUInt32LE(offset, 12);
    offset += png.length;
    entries.push(e);
  }
  return Buffer.concat([header, ...entries, ...images.map((i) => i.png)]);
}

async function main() {
  const { default: dataset } = await import("permit-rulebook-data/data/dataset.json", { with: { type: "json" } });
  const { datasetMeta } = await import("permit-rulebook-data");
  // The product's own words and the card's own layout, imported rather than
  // retyped. Node strips the types; the specifiers are `.ts` because Node
  // resolves a `.js` specifier literally and there is no build step here.
  const { PRODUCT_NAME, TAGLINE } = await import("../src/lib/copy.ts");
  const { socialCardFacts, socialCardHtml } = await import("../src/lib/social-card.ts");
  const tokens = readFileSync(join(root, "tokens.css"), "utf8");
  const facts = socialCardFacts(dataset, datasetMeta(dataset).newest_retrieved_at, {
    product: PRODUCT_NAME, tagline: TAGLINE,
  });

  if (check) {
    const missing = ["favicon.svg", "favicon.ico", ...ICON_SIZES.map((s) => `favicon-${s}.png`), "social-card.png", SIDECAR]
      .filter((f) => !existsSync(join(publicDir, f)));
    if (missing.length) throw new Error(`public/${missing.join(", public/")} missing — run: npm run assets`);

    const card = readFileSync(join(publicDir, "social-card.png"));
    const w = card.readUInt32BE(16), h = card.readUInt32BE(20);
    if (w !== CARD.width || h !== CARD.height)
      throw new Error(`social-card.png is ${w}x${h}, must be ${CARD.width}x${CARD.height}`);

    const drawn = JSON.parse(readFileSync(join(publicDir, SIDECAR), "utf8"));
    const differences = Object.entries(facts)
      .filter(([k, v]) => JSON.stringify(drawn[k]) !== JSON.stringify(v))
      .map(([k, v]) => `${k}: the image says ${JSON.stringify(drawn[k])}, the dataset says ${JSON.stringify(v)}`);
    if (differences.length)
      throw new Error(`social-card.png no longer tells the truth — run: npm run assets\n  ${differences.join("\n  ")}`);

    console.log(JSON.stringify({
      level: "info", msg: "assets present and true",
      social_card: `${w}x${h}`, routes: facts.routes, read: facts.read,
    }));
    return;
  }

  mkdirSync(publicDir, { recursive: true });
  const svg = readFileSync(join(publicDir, "favicon.svg"), "utf8");
  const images = [];
  for (const size of ICON_SIZES) {
    const out = join(publicDir, `favicon-${size}.png`);
    const dir = join(tmpdir(), `permit-rulebook-icon-${size}`);
    mkdirSync(dir, { recursive: true });
    writeFileSync(join(dir, "favicon.svg"), svg, "utf8");
    writeFileSync(join(dir, "page.html"), markPage(size), "utf8");
    execFileSync(chromePath(), [
      "--headless", "--disable-gpu", "--hide-scrollbars", "--force-device-scale-factor=1",
      `--window-size=${size},${size}`, `--screenshot=${out}`,
      pathToFileURL(join(dir, "page.html")).href,
    ], { stdio: "ignore" });
    rmSync(dir, { recursive: true, force: true });
    images.push({ size, png: readFileSync(out) });
  }
  writeFileSync(join(publicDir, "favicon.ico"), ico(images));

  shoot(socialCardHtml(facts, tokens), CARD.width, CARD.height, join(publicDir, "social-card.png"));
  writeFileSync(join(publicDir, SIDECAR), `${JSON.stringify(facts, null, 2)}\n`, "utf8");

  console.log(JSON.stringify({
    level: "info", msg: "assets rendered",
    files: [...ICON_SIZES.map((s) => `favicon-${s}.png`), "favicon.ico", "social-card.png", SIDECAR],
    routes: facts.routes, read: facts.read,
  }));
}

await main();
